import type { ShopCategory } from "@/shop/types";

// Visible text for the online shop, cart and product pages.
const en = {
  meta: {
    title: "Shop Phone Accessories Online — Cases, AirPods & JBL | TIC Wireless",
    description:
      "Shop phone cases, tempered glass, AirPods, Galaxy Buds, JBL speakers, smartwatches and chargers from TIC Wireless on Hillcroft in Houston.",
    breadcrumb: ["Home", "Shop"],
  },
  hero: {
    kicker: "TIC Wireless online shop",
    title: ["The accessory wall,", "now online."],
    body: "Cases, glass, AirPods, Galaxy Buds, JBL speakers, smartwatches and chargers — the same gear we stock on Hillcroft.",
    search: "Search cases, AirPods, JBL…",
    preview: "Preview store · online checkout coming soon",
  },
  categories: {
    all: "All",
    cases: "Cases",
    "screen-protection": "Screen protection",
    earbuds: "Earbuds & headphones",
    speakers: "Speakers",
    wearables: "Smartwatches",
    power: "Chargers & power",
    gaming: "Gaming",
    more: "More",
  } satisfies Record<ShopCategory | "all", string>,
  sort: {
    label: "Sort",
    featured: "Featured",
    "price-asc": "Price: low to high",
    "price-desc": "Price: high to low",
    name: "Name",
  },
  results: (n: number) => `${n} product${n === 1 ? "" : "s"}`,
  empty: "No products match your search.",
  clear: "Clear filters",
  badge: { "best-seller": "Best seller", new: "New", sale: "Sale" },
  add: "Add to cart",
  added: "Added",
  quickAdd: "Add",
  choose: "Choose options",
  from: "From",
  soldOut: "Sold out",
  inStock: "In stock",
  quantity: "Quantity",
  features: "Highlights",
  related: "You might also like",
  trust: [
    ["Real store on Hillcroft", "See it, hold it, ask questions — 3640 Hillcroft St."],
    ["Se habla español", "Help in English or Spanish, in store or on the phone."],
    ["Need it today?", "Call us to check stock and set an item aside."],
  ],
  financing: {
    title: "Bigger purchase?",
    body: "Phones, consoles and laptops are available with lease-to-own, no credit needed.",
    cta: "See financing",
  },
  questions: "Questions about this item?",
  cart: {
    title: "Your cart",
    empty: "Your cart is empty.",
    browse: "Browse accessories",
    subtotal: "Subtotal",
    note: "Taxes and shipping are calculated at checkout.",
    checkout: "Checkout",
    remove: "Remove",
    continue: "Continue shopping",
    open: "Open cart",
    items: (n: number) => `${n} item${n === 1 ? "" : "s"}`,
  },
  previewCheckout: {
    title: "Checkout is in preview",
    body: "When the Shopify store is connected, this button opens secure Shopify checkout with your cart. For now, call or visit us and we'll get you set up.",
    call: "Call to order",
    close: "Keep shopping",
  },
  checkoutError: "Couldn't start checkout. Please try again or call us.",
  homeTeaser: {
    kicker: "Shop online",
    title: "Accessories, a tap away.",
    body: "Cases, AirPods, Galaxy Buds, JBL and more from our shelves to your cart.",
    cta: "Shop all accessories",
  },
};

export type ShopCopy = typeof en;

const es: ShopCopy = {
  meta: {
    title: "Accesorios para Celular en Línea — Fundas, AirPods y JBL | TIC Wireless",
    description:
      "Compra fundas, micas de vidrio templado, AirPods, Galaxy Buds, bocinas JBL, relojes inteligentes y cargadores de TIC Wireless en Hillcroft, Houston.",
    breadcrumb: ["Inicio", "Tienda"],
  },
  hero: {
    kicker: "Tienda en línea de TIC Wireless",
    title: ["La pared de accesorios,", "ahora en línea."],
    body: "Fundas, micas, AirPods, Galaxy Buds, bocinas JBL, relojes inteligentes y cargadores — lo mismo que tenemos en Hillcroft.",
    search: "Busca fundas, AirPods, JBL…",
    preview: "Tienda en vista previa · pago en línea muy pronto",
  },
  categories: {
    all: "Todo",
    cases: "Fundas",
    "screen-protection": "Micas y protectores",
    earbuds: "Audífonos",
    speakers: "Bocinas",
    wearables: "Relojes inteligentes",
    power: "Cargadores",
    gaming: "Gaming",
    more: "Más",
  },
  sort: {
    label: "Ordenar",
    featured: "Destacados",
    "price-asc": "Precio: menor a mayor",
    "price-desc": "Precio: mayor a menor",
    name: "Nombre",
  },
  results: (n: number) => `${n} producto${n === 1 ? "" : "s"}`,
  empty: "Ningún producto coincide con tu búsqueda.",
  clear: "Quitar filtros",
  badge: { "best-seller": "Más vendido", new: "Nuevo", sale: "Oferta" },
  add: "Agregar al carrito",
  added: "Agregado",
  quickAdd: "Agregar",
  choose: "Elegir opciones",
  from: "Desde",
  soldOut: "Agotado",
  inStock: "Disponible",
  quantity: "Cantidad",
  features: "Características",
  related: "También te puede gustar",
  trust: [
    ["Tienda real en Hillcroft", "Velo, tócalo y pregunta — 3640 Hillcroft St."],
    ["We speak English", "Te atendemos en español o inglés, en tienda o por teléfono."],
    ["¿Lo necesitas hoy?", "Llámanos para revisar inventario y apartarlo."],
  ],
  financing: {
    title: "¿Una compra más grande?",
    body: "Celulares, consolas y laptops con opción a compra, sin necesidad de crédito.",
    cta: "Ver financiamiento",
  },
  questions: "¿Preguntas sobre este producto?",
  cart: {
    title: "Tu carrito",
    empty: "Tu carrito está vacío.",
    browse: "Ver accesorios",
    subtotal: "Subtotal",
    note: "Impuestos y envío se calculan al pagar.",
    checkout: "Pagar",
    remove: "Quitar",
    continue: "Seguir comprando",
    open: "Abrir carrito",
    items: (n: number) => `${n} artículo${n === 1 ? "" : "s"}`,
  },
  previewCheckout: {
    title: "El pago está en vista previa",
    body: "Cuando la tienda de Shopify esté conectada, este botón abrirá el pago seguro de Shopify con tu carrito. Por ahora, llámanos o visítanos y te ayudamos.",
    call: "Llamar para ordenar",
    close: "Seguir comprando",
  },
  checkoutError: "No pudimos iniciar el pago. Intenta de nuevo o llámanos.",
  homeTeaser: {
    kicker: "Compra en línea",
    title: "Accesorios a un toque.",
    body: "Fundas, AirPods, Galaxy Buds, JBL y más, de nuestros estantes a tu carrito.",
    cta: "Ver todos los accesorios",
  },
};

export const SHOP_COPY = { en, es };
